name: HACS Validate

on:
  push:
    paths:
      - "custom_components/virtualpoolcare/manifest.json"
      - "hacs.json"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate HACS Integration
        uses: hacs/action@main
        with:
          category: "integration"
          ignore: "brands"