name: HACS Validate

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate HACS Integration
        uses: hacs/action@main
        with:
          category: "integration"
          ignore: "brands"