name: Hassfest

on:
  push:
    paths:
      - "custom_components/virtualpoolcare/manifest.json"
      - "custom_components/virtualpoolcare/sensor.py"
      - "custom_components/virtualpoolcare/const.py"
      - "custom_components/virtualpoolcare/__init__.py"

jobs:
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master