name: Hassfest

on:
  push:
    paths:
      - "manifest.json"
      - "sensor.py"
      - "const.py"
      - "__init__.py"

jobs:
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install homeassistant
      - name: Run hassfest
        run: |
          python -m script.hassfest